// csv — minimal CSV-serialisering. Ingen extern dependency för en enda tabell.
import type { GameMetrics } from './runGame.js'

const COLUMNS = [
  'policy',
  'seed',
  'ending',
  'finalTurn',
  'treasury',
  'doomsdayPeak',
  'contracts',
  'marketSharePct',
  'rivalWinPct',
  'disqualifiedRivalBidPct',
  'grossMarginPct',
  'heatOver40SharePct',
  'rivalContractsWon',
  'rivalAttributionShare',
  'voidedContracts',
  'retoolingTurns',
  'stationsBurned',
  'sectorsChangedSide',
  'frontMovementTotal',
  'formationsChangedStatus',
  'factionsChangedAlignment',
  'officialsReplaced',
  'advanceSharePct',
  'minTreasuryTurns1to6',
  'ceasefires',
  'standingOrderAlarms',
  'buyoutReview',
  'submittedItems',
  'rejectedItems',
  'designs',
  'designBreakthroughs',
  'casualties',
  'battleProven',
  'gapShocks',
  'firstInPlace',
  'falseGapsCreated',
  'youngDesignRevenuePct',
  'programmes',
  'programmesEntered',
  'programmesWon',
  'programmesSplit',
  'programmesLost',
  'traces',
  'tracesSurfaced',
  'voidedByScandal',
  'suspensions',
  'contractsWonViaProgramme',
  'civilRevenue',
  'civilSharePct',
  'exportBreaches',
  'licencesGranted',
  'licenseeRivals',
  'skunkDesigns',
  'fieldOccasions',
  'fieldTrials',
  'upgradedDesigns',
  'kitContracts',
  'studiedSystems',
  'lowballs',
  'programmeSabotages',
  'rivalReports',
  'reportsConfirmed',
  'reportsFalse',
  'lineUtilizationPct',
  'peakLineUtilizationPct',
  'linesBuilt',
  'lateContracts',
  'worksBuilt',
  'worksBuiltKinds',
  'worksExpansions',
  'outsourcedSharePct',
  'runInLevel',
  'strikes',
  'breakdowns',
  'stockValue',
  'foreignWorksLost',
  'operatingDecisionPct',
  'plotFull',
  'runInSeries',
  'runInSharePct',
] as const satisfies readonly (keyof GameMetrics)[]

function csvField(value: string | number): string {
  const s = String(value)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

export function toCsv(rows: readonly GameMetrics[]): string {
  const header = COLUMNS.join(',')
  const lines = rows.map((row) => COLUMNS.map((col) => csvField(row[col])).join(','))
  return [header, ...lines].join('\n') + '\n'
}
